# Generated by Django 2.2.7 on 2019-11-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
