# Generated by Django 2.2.7 on 2019-11-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0002_auto_20191114_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='email',
        ),
    ]
